### ISSUE TITLE
`logging.detectedResource` does not return "cloud_run_revision" on Cloud Run

### ISSUE THREAD

**Issue by averikitsch** [googleapis/nodejs-logging#1127]
#### Environment details

  - OS: Container (base node:12-slim)
  - Node.js version: 12
  - npm version: 7.18.1
  - `@google-cloud/logging` version: 9.5.4

#### Steps to reproduce

  1. Create service w/ code snippet (see full service [here](https://github.com/averikitsch/nodejs-docs-samples/blob/cloud-logging/run/helloworld/index.js)):
```
  const {Logging} = require('@google-cloud/logging');
  const logging = new Logging();
  await logging.setProjectId();
  await logging.setDetectedResource();
  console.log(logging.projectId);
  console.log(logging.detectedResource); // { type: 'global' }
```
  2. Deploy to Cloud Run:
```
gcloud beta run deploy logging-test --source .
```

3. Inspect logs:
```
console.log(logging.detectedResource); 
// outputs { type: 'global' }
```

**Comment by ramicohen303** [comment]
I encountered the same issue. Any ETA on a fix for this?

**Comment by minherz** [comment]
I will have a look into it during this week (week 35). However, it will be helpful to get a better understanding about the problem. According to the [public documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) the resource metadata is described by the top-level `"resource"` field. The [resource metadata](https://cloud.google.com/logging/docs/reference/v2/rest/v2/MonitoredResource) defines the `"type"` field that describes the monitored resource type.
In the provided examples you can see that the resource type of the log entries is `"cloud_run_revision"` which is the expected resource type for Cloud Run.

The additional field `jsonPayload.resource.type` is indeed misleading and the field's value is incorrect. However, it should not be a blocker since developers have to follow the official documentation when inspecting the fields.

The fix to remove the duplication will be applied as soon as possible.

**Comment by daniel-sanche** [comment]
I will also look into the environment tests soon, since they are passing and they should be catching this
