### ISSUE TITLE
logSync ignores log_id when it generates logName field

### ISSUE THREAD

**Issue by anton-yarchuk** [googleapis/nodejs-logging#1207]
`logging.logSync` function ignores provided `log_name` and generates standard `logName` field.

#### Environment details

  - OS: Ubuntu 20.4
  - Node.js version: 12.22.5
  - npm version: 6.14.14
  - `@google-cloud/logging` version: 9.6.6

#### Steps to reproduce

```js
const logging = new Logging();

await logging.setProjectId(); // I've tested with and without these two lines
await logging.setDetectedResource();

const log = logging.logSync('hello-log-sync');

const meta = {
  severity: 'INFO',
  labels: {
    iHaveLabels: 'too',
  },
};
const data = {
  some: 'data',
};

await log.write(log.entry(meta, data));
  ```

#### Expected results:

- 'hello-log-sync' is used for generating `logName`

#### Actual results:
![image](https://user-images.githubusercontent.com/32197676/148850721-b924e9cb-93e8-4fca-aeb0-82381b8bcd43.png)
1. valid `logName` is a part of the `jsonPayload` for some reason
2. `data` ended up in `message`, but I didn't specified any messages
3. `labels` looks ok
4. standard `logName` is generated instead

#### Notes:
**What if I will switch to `logging.log` instead?**
I works A-OK, but please check the next question
 
**Why I'm using logSync?**
I want to have `executionId` label autogenerated which is not available in `logging.log`
  
**can I use `console.log` instead?**
Yes, but from what I know, I can't specify `log name` and affect `logName` using `console.log` which is critical for me

**Comment by anton-yarchuk** [comment]
Thanks, @losalex for the reply

A bit more context, MB it will help:
I came from [another issue](https://github.com/googleapis/nodejs-logging/issues/591), which is related to the lack of `executionId` when you are using regular `Log` in background tasks. This issue is quite old btw. 

At the very end of the discussion (the very last comment), @0xSage suggested to use `LogSync` instead or regular `Log`. 
Indeed, with `LogSync` `executionId` label is added, but if you will check the code in his comment you will notice that  he had the same issue with duplicated `logName`:

![image](https://user-images.githubusercontent.com/32197676/150518129-b3871b5e-c780-47f0-8e67-7b1d58c9e6b8.png)

**Comment by losalex** [comment]
Thanks @anton-yarchuk - I am still looking for the issue and examining possible solution. I believe the problem is that we do not wrap log entries with [JSON write request](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write) which is used in [Log.write](https://github.com/googleapis/nodejs-logging/blob/1a0b59137b9d0bd24dc8ac5e3b46c4b78a07c61d/src/log.ts#L922) method. As for missing execution ID when [Log.write](https://github.com/googleapis/nodejs-logging/blob/1a0b59137b9d0bd24dc8ac5e3b46c4b78a07c61d/src/log.ts#L922) is used - I am following up with Cloud Functions team on this.

**Comment by losalex** [comment]
@anton-yarchuk, 
Thanks for your patience - I looked deeper into an issue and seems currently there is no fast solution for a problem. The issue is that when `LogSync` is used in cloud (e.g. Cloud Functions), by default all logging output goes to `stdout` which is picked by the agent running on every node. Unfortunately, the agent need a fix to support [JSON write request](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write) or provide alternative solution to specify desired [LOG_ID](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#:~:text=%5B-,LOG_ID,-%5D%20must%20be%20less). I also filed an issue with missing `executionId` on our Cloud Function team. Until those issues are fixed, I do not have any alternative suggestion to solve this problem.
Please let me know if you have any other comments/asks

**Comment by anton-yarchuk** [comment]
@losalex 
Got it, thanks for letting me know. :+1: 
Will wait for a fix
