### ISSUE TITLE
Can we use this for sequential logging on a react native application ?

### ISSUE THREAD

**Issue by kopax-polyconseil** [googleapis/nodejs-logging#1260]
Hello,

We use Sentry for error reporting in our react native iOS and Android application.

This is not convenient for debugging purpose, we would like to configure some sequential logging but we can't find a good service.

Our platform is hosted on GCP, do you think we can use this client side on a react native app or is it only for server side ?

Best regards and thanks!

**Comment by losalex** [comment]
Thank you @kopax-polyconseil for reaching out and sorry for late response.
Unfortunately, this library is designed to be used on server side and currently there are no plans to make this library to be client side compatible. And I never tried to run this library on a client side :-)
As for client side logging, we have the experimental library [stackdriver-errors-js](https://github.com/GoogleCloudPlatform/stackdriver-errors-js) which provides an ability to integrate directly with [Google Cloud Error Reporting](https://cloud.google.com/error-reporting/), so it could be used at least to report errors. Thats said, I am not sure if that will work with your native iOS/Android application - please take a look and let me know if it could work, I would really appreciate your input on this.

**Comment by kopax-polyconseil** [comment]
Hello @losalex , we already use Sentry for error reporting and it is "better", what we are looking now is to activate some sequential logging on demand on specific device. Do you have another solution to recommend ?

**Comment by losalex** [comment]
Hi @kopax-polyconseil, I am not aware of any other client side solution which I can recommend. 
If you have any server side components in your solution, you could definitely leverage those to propagate logging to Cloud Logging, but as for clients I am not aware of any other solution.
One thing to mention, there is a blog which describes some technique to collect logs from [browser](https://medium.com/google-cloud/collecting-browser-console-logs-in-stackdriver-fa388a90d32b,) however I am not sure if that would solve your problem since it still assumes you will need to run some server side component in GCP.

**Comment by losalex** [comment]
@kopax-polyconseil, I am going to close this issue - feel free to reactivate it or comment if you have any more questions. Thank you!
