### ISSUE TITLE
Update reference to gax-nodejs to 3.5.7 for new protobuf version

### ISSUE THREAD

**Issue by JamesWPritchett** [googleapis/nodejs-logging#1405]
**Is your feature request related to a problem? Please describe.**
Vulnerability reports show TaffyDB as a risk.  TaffyDB is used by JSDoc which is used by protobufjs-cli which is used by gax-nodejs which is used by this library.
JSDoc recently updated their library to no longer use TaffyDB. 
protobufjs-cli updated their library to use the new JSDoc library
Gax-NodeJs recently updated their library to use the new protobufjs-cli library.
Now, we need this library to update the Gax-NodeJS references
 **Describe the solution you'd like**
Update version of gax-nodejs used by this liibrary to 3.5.7
 **Describe alternatives you've considered**
none
 **Additional context**
[https://nvd.nist.gov/vuln/detail/CVE-2019-10790](https://nvd.nist.gov/vuln/detail/CVE-2019-10790)
[https://cwe.mitre.org/data/definitions/668.html](https://cwe.mitre.org/data/definitions/668.html)

![image](https://user-images.githubusercontent.com/10659308/219771687-c0243bdb-4983-4c96-b48f-e0f1931f5236.png)

**Comment by JamesWPritchett** [comment]
Can we get the priority bumped up on this one?  it's a security issues, not a "nice to have"

**Comment by meredithslota** [comment]
Hi @JamesWPritchett — apologies for the delay, I think this slipped through our triage process since you had added the `type: feature request` label when the issue was filed, and we triage feature requests on a different cadence than security issues. I believe we can update to gax-nodejs 3.5.8 now. Let me see if there are any blockers here.
