### ISSUE TITLE
Generated insertId with leading dots

### ISSUE THREAD

**Issue by yfyau** [googleapis/nodejs-logging#1500]
### Question
The auto generated insertId has strange leading dots. 
While this isn't a big deal, I'm wondering if I'm missing some properties needed to make it work. 😬

![Screenshot 2024-04-23 at 12 19 49 PM](https://github.com/googleapis/nodejs-logging/assets/37103700/82e78d33-befb-472d-81f3-2ed44ec938a6)

**Comment by cindy-peng** [comment]
Hi @yfyau, this is expected format and behavior. If `insertId` is omitted in [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry), our logging API will assign a unique identifier as `insertID` using [eventID library](https://github.com/google/eventid-js). Since Javascript timestamps only have millisecond resolution making them unsuitable for the purpose of building monotonically increasing local ids, our service does use `insertId` from `eventId` as a secondary ordering for entries with the same timestamp.

**Comment by yfyau** [comment]
Got it. Thx 👍
