### ISSUE TITLE
Constructor fails with "RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds"

### ISSUE THREAD

**Issue by carusooo** [googleapis/nodejs-logging#1520]
1) Is this a client library issue or a product issue?
Client library

2) Did someone already solve this?
No

3) Do you have a support contract?
Yes, but filing here for others visibility

#### Environment details

  - OS: node22-alpine
  - Node.js version: 22.2.0
  - npm version: 10.7.0
  - `@google-cloud/logging` version: 11.2.0

#### Steps to reproduce

  1. Create an instance of the client like so 
  ```typescript
      const logging = new Logging();
      const log = logging.log('my-server', {
        maxEntrySize: 100000,
      });
  ```
  2. The following stack trace is thrown
  
  ```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/app/backend/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/app/backend/node_modules/protobufjs/src/writer.js:453:14)
    at /app/backend/node_modules/@grpc/proto-loader/build/src/index.js:177:109
    at Array.map (<anonymous>)
    at createPackageDefinition (/app/backend/node_modules/@grpc/proto-loader/build/src/index.js:177:39)
    at Object.fromJSON (/app/backend/node_modules/@grpc/proto-loader/build/src/index.js:230:12)
    at GrpcClient.loadProtoJSON (/app/backend/node_modules/google-gax/build/src/grpc.js:228:51)
    at new ConfigServiceV2Client (/app/backend/node_modules/@google-cloud/logging/build/src/v2/config_service_v2_client.js:136:38)
    at new Logging (/app/backend/node_modules/@google-cloud/logging/build/src/index.js:140:30)
 ```

This was working earlier today 22 Aug 2024 6p PDT, and began failing with builds created around 22 Aug 2024 9p PDT which leads me to believe that some change in an underlying library caused this issue.

**Comment by carusooo** [comment]
I retried with smaller values for `maxEntrySize` 5000, and without supplying it at all and still got the same error

**Comment by stijnv404** [comment]
this is a really serious issue by the way, currently none of our projects can start new container instances (we use Google CloudRun) because the container start fails with the above error

so it's not only happening to new projects, but also existing projects that already have node_modules stored in their container image, so it's likely a server-side issue at google causing this

we're running well over a hundred projects, so if any of them need scaling or a container needs to restart due to a crash or anything, that means downtime until this issue is fixed

I hope this will be resolved fast and see a statement on how this happened and will be prevented in the future

**Comment by carusooo** [comment]
Some additional data points, this affects multiple GCP node libraries (including secretManager) and appears to be in [this code block](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L372) where the protos are loaded from the server (I am guessing?) where the code hasn't changed in 5 years

**Comment by carusooo** [comment]
This is due to a [nodeJS](https://github.com/nodejs/node/issues/54518) issue with 22.7.0
