### ISSUE TITLE
Avoid deprecated dependencies

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging#277]
I see the following on [a sample-tests build](https://source.cloud.google.com/results/invocations/18676211-92af-4883-8b83-a533a543fae6/targets):

```
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```

Let's resolve these.

**Comment by JustinBeckwith** [comment]
Yeah, text-encoding is being brought in by the latest version of sinon :/  I will look into the CIrcularJSON thing.

**Comment by JustinBeckwith** [comment]
So good news, bad news. 

Good news - the [circular-json issue](https://github.com/eslint/eslint/pull/11314) has been fixed in eslint, and will be in the next release (which should be relatively soon. 

Bad mews - the [text-encoding](https://github.com/sinonjs/nise/issues/66) issue is unresolved, and basically boils down to someone adopting ownership of the model.  Sinon is pretty important, so I can't imagine us dropping that.

**Comment by JustinBeckwith** [comment]
Both of these are fixed!
