### ISSUE TITLE
include 256 kb max log line size in documentation

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-logging#531]
see: https://github.com/googleapis/nodejs-logging/issues/520

**Comment by zamnuts** [comment]
From [logging.proto](https://github.com/googleapis/nodejs-logging/blob/0239b81ed816412e2a06bcfaaa347552cb00dc29/protos/google/logging/v2/logging.proto#L73-L86), it appears that the 1000 object and 10MB limit also apply when batching to `log.write`. I don't see an indication, docs or otherwise, of internal buffering to the underlying RPC.

**Comment by alamothe** [comment]
For the 256k limit, I assume it applies to utf-8 encoded message?
