### ISSUE TITLE
refactor tests to have less race conditions

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-logging#550]
Our system tests call `log.delete` as an `after` hook, it's frequently the case that a log line fails to be deleted, even after `>30s` of waiting:

```bash
delete of system-test-logs-df4ebe77-8e09-432b-b971-2adacc2e18c4 failed retries = 1
delete of system-test-logs-df4ebe77-8e09-432b-b971-2adacc2e18c4 failed retries = 2
delete of system-test-logs-df4ebe77-8e09-432b-b971-2adacc2e18c4 failed retries = 3
delete of system-test-logs-a0d900e6-1005-43e0-bf10-b15750367cae failed retries = 1
delete of system-test-logs-a0d900e6-1005-43e0-bf10-b15750367cae failed retries = 2
delete of system-test-logs-a0d900e6-1005-43e0-bf10-b15750367cae failed retries = 3
delete of system-test-logs-dbb4fdef-2234-42b5-acd5-e413bac75c48 failed retries = 1
delete of system-test-logs-dbb4fdef-2234-42b5-acd5-e413bac75c48 failed retries = 2
delete of system-test-logs-dbb4fdef-2234-42b5-acd5-e413bac75c48 failed retries = 3
```

we should dig into this further and, if need be, log an issue with the upstream API.

**Comment by AVaksman** [comment]
Perhaps implement a logic to delete logs on a subsequent system-test.

collect all log IDs that failed to be deleted and write them in another log with hard coded name like `'to_delete'`. In the beginning of every system-test check for entries in that log?

**Comment by bcoe** [comment]
Our tests fail to cleanup after each test case effectively, due to what appear to be race conditions.

I've labeled this as `process`, rather than a `bug`, as tests have been running successfully as of late.

**Comment by stephenplusplus** [comment]
When logs are attempted to be deleted in the after hook, it retries a few times before giving up:

```js
// attempt to delete log entries multiple times, as they can
// take a variable amount of time to write to the API:
```

Right now, it retries after 5 seconds (`WRITE_CONSISTENCY_DELAY_MS`). In the past, I have needed to bump that up to 60 seconds to get passing tests. We must have come back down to 5 because the waiting became excessive.

Another problem could be this scenario:

  - Test block (an `it`) gets a reference to a Log (no remote operation, just a Log object)
  - Log object is stored in local array (to the `describe`)
  - Test block tries to create a log entry, but fails
  - After hook iterates over local array of Log objects, but **doesn't know if they were actually created**

We should be able to handle this by simply ignoring `after` hook errors that indicate the log failed to be deleted because it doesn't exist. PR incoming for that.
