### ISSUE TITLE
Warning: insecure environment read function 'getenv' used

### ISSUE THREAD

**Issue by ilyalavrenov** [googleapis/nodejs-logging#555]
#### Environment details

  - OS: node:8.12-alpine Docker image (based on Alpine 3.8.1)
  - Node.js version: 8.12.0
  - npm version: 6.4.1
  - `@google-cloud/logging` version: 4.5.2

#### Steps to reproduce

It's a small papercut, but we are seeing frequent `Warning: insecure environment read function 'getenv' used` messages in our logs, even with `GRPC_VERBOSITY="ERROR"` set (as mentioned in some related issues like https://github.com/grpc/grpc/issues/8104). This seems to be fixed in v5.x of this package, but is there any chance of a hotfix for v4? We have a few projects still using Node 8.12 that haven't yet been upgraded, and v5 doesn't support it due to `Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0` 

```
$ tail -n +1 Dockerfile package.json index.js
==> Dockerfile <==
FROM node:8.12-alpine

ENV GRPC_VERBOSITY "ERROR"
ENV NODE_ENV "production"

WORKDIR /opt/app
COPY package*.json ./
RUN npm install
COPY index.js ./

ENTRYPOINT ["npm", "start"]

==> package.json <==
{
  "name": "grpctest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/logging": "^4.5.2"
  }
}

==> index.js <==
const {Logging} = require('@google-cloud/logging');
const logging = new Logging();

console.log('hello!');

$ docker build -t grpctest . && docker run grpctest
Sending build context to Docker daemon  40.45kB
Step 1/8 : FROM node:8.12-alpine
 ---> df48b68da02a
Step 2/8 : ENV GRPC_VERBOSITY "ERROR"
 ---> Using cache
 ---> 98014b20a1a0
Step 3/8 : ENV NODE_ENV "production"
 ---> Using cache
 ---> 319468e5292e
Step 4/8 : WORKDIR /opt/app
 ---> Using cache
 ---> fffdbc6dcbe2
Step 5/8 : COPY package*.json ./
 ---> 3fc583dd977e
Step 6/8 : RUN npm install
 ---> Running in 0c37bdd77c67

> grpc@1.22.2 install /opt/app/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download
[grpc] Success: "/opt/app/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-musl/grpc_node.node" is installed via remote

> protobufjs@6.8.8 postinstall /opt/app/node_modules/protobufjs
> node scripts/postinstall

npm WARN grpctest@1.0.0 No description
npm WARN grpctest@1.0.0 No repository field.

added 221 packages from 159 contributors and audited 972 packages in 12.779s
found 0 vulnerabilities

Removing intermediate container 0c37bdd77c67
 ---> a88f678e4088
Step 7/8 : COPY index.js ./
 ---> 61568936b673
Step 8/8 : ENTRYPOINT ["npm", "start"]
 ---> Running in c87e9e775bfa
Removing intermediate container c87e9e775bfa
 ---> c1c461f1e683
Successfully built c1c461f1e683
Successfully tagged grpctest:latest

> grpctest@1.0.0 start /opt/app
> node ./index.js

D0807 21:49:19.225377200      16 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used
hello!
```

**Comment by JustinBeckwith** [comment]
Greetings!  And thanks for the bug report.  Sadly, in part due to the significance of the fix, there's no way we could realistically backport this to the 4.x release line.  The change that happened in 4.x => 5.x was a move from the c-core native version of grpc over to a totally different implementation: grpc-js.  grpc-js requires HTTP/2 to be in node core, which didn't make it out of experimental mode until Node.js 8.13:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.13.0

While we try to support older releases of 8.x, in this particular case it just wasn't possible.  I know that these kinds of upgrades come with risks - but have y'all tried an upgrade to node.js 8.13 in your container?  Finding breaking changes in newer point releases of node.js is very rare (though I understand there is risk)
