### ISSUE TITLE
add support for populating gke container name

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-logging#673]
It would make it easier to search GKE logs if we figured out a way to populate a container name.

see: #525

**Comment by deedf** [comment]
This line: https://github.com/googleapis/nodejs-logging/blob/7c90bbe93daa32c265e5867f7962aad32407fe6e/src/metadata.ts#L122

creates a 'k8s_container' resource descriptor with only the cluster_name and namespace_name fields.

https://cloud.google.com/monitoring/api/resources#tag_gke_container says the following fields are required:

project_id: The identifier of the GCP project associated with this resource, such as "my-project".
cluster_name: The name for the cluster the container is running in.
namespace_id: The identifier for the cluster namespace the container is running in.
instance_id: The identifier for the Compute Engine instance the container is running in.
pod_id: The identifier for the pod the container is running in.
container_name: The name of the container.
zone: The zone for the instance.

I think project_id is set correctly by default already, pod_id, container_name and zone are empty, which is a problem.

**Comment by michaelbarnard** [comment]
Any update on this ticket? Or a possible workaround?

**Comment by mlarcher** [comment]
@michaelbarnard As a workaround you can just not user this package at all, and log to the console. 

The only thing for us that wasn't working out of the box and made us use this lib was severity levels formatting so that they are picked up by stackdriver, but it turned out that by setting them manually we could just not use the lib at all and get the expected result.

This may not fit your use case, but if you're interested you'll find more info on https://github.com/googleapis/nodejs-logging-winston/issues/386#issuecomment-602195498

**Comment by michaelbarnard** [comment]
@mlarcher Was just considering this lib as an alternative to the winston version to reduce the memory footprint of our pods. We are currently running the winston via the console.log. Guess that is the best way currently. But I will keep my eye on that issue you referenced. Thank you.
