### ISSUE TITLE
Trimmed messages does not includes severity

### ISSUE THREAD

**Issue by lechen26** [googleapis/nodejs-logging#826]
Hi

we are using winston logging library to stackdriver.
we've noticed recently that when we have vary long message entry , the messages are trimmed and splitted to multiple messags.
i've noticed thats due to the last addition of maxEntrySize , which is great.
the problem is, when its happens, the severity get ignores, and all messages appears as INFO.

i would expect the split operation for the message will includes also the rest of the json for all messages including the severity.

how can we overcome this? except just trimming the message inside the formatter?

thanks

**Comment by losalex** [comment]
@lechen26 , thank you very much for filing an issue and really sorry for such a late response.
I believe that this issue was resolved by [1177](https://github.com/googleapis/nodejs-logging/pull/1177) - it also makes sure that fields truncated reside in `jsonPayload` or `textPayload` only.
Closing this issue for now - feel free to reactivate it os ask more questions if you have any.
