### ISSUE TITLE
Types: `configService` and `loggingService` clients are optional and any

### ISSUE THREAD

**Issue by lukasschwab** [googleapis/nodejs-logging#938]
Hello! Thanks for your work maintaining this client library.

+ Node version: 12.16.1
+ `@google-cloud/logging` version: 8.0.9

In the built declaration file for this library, ./build/src/index.d.ts, the new v2 client types are unexpected.

The expected types are exported here: https://github.com/googleapis/nodejs-logging/blob/4325e3b110d88ecbda312bc36330c7c3685a58c2/src/v2/index.ts#L19-L21

And imported in `index.ts`: https://github.com/googleapis/nodejs-logging/blob/4325e3b110d88ecbda312bc36330c7c3685a58c2/src/index.ts#L41

But the `require` expression yields `declare const v2: any;` in the declaration file, so the exported types for `Logging.configService` and `Logging.loggingService` is `any | null` and the exported type for `v` is `any`.

![Screen Shot 2020-11-06 at 18 17 36](https://user-images.githubusercontent.com/4955943/98429591-60520480-205c-11eb-9b4b-ad31b91403b0.png)

If there's anything I can clarify here, please don't hesitate to let me know!

**Comment by lukasschwab** [comment]
@simonz130 I've been keeping tabs on recent releases; glad to see the Log Buckets APIs are being improved (e.g. with https://github.com/googleapis/nodejs-logging/commit/c9a69da3cf4ec3e87f30afc22344191a3e43e26a).

Is this nullability the intended behavior, or was I right to conclude it's a bug?

**Comment by Daniel-Sanche** [comment]
Hey Lukas. I'm not too familiar with Node, but maybe I can give some context before one of the node experts jumps in.

One thing to keep in mind is that the code in the v2 folder is auto-generated, and some unfriendliness is to be expected when interacting with the autogenerated code. Our eventual goal is to have end-users using the more friendly idomatic wrappers around the v2 clients, rather then interacting with them directly. See the code in the [samples directory](https://github.com/googleapis/nodejs-logging/blob/4325e3b110d88ecbda312bc36330c7c3685a58c2/samples/logs.js). 

Of course, for newer features like the Log Buckets API, we don't quite have coverage outside of the v2 clients yet, but we're working on it

**Comment by nicoleczhu** [comment]
Hi @lukasschwab , this is intentional. 

As @Daniel-Sanche mentioned, we have the autogenerated library (files under directory v2/). And then on top of that, we have handwritten logic to make the library easier to use. 

In this case, in the handwritten layer, we intentionally made configservice optional. See [line 252](https://github.com/googleapis/nodejs-logging/blob/7cab3c5990c51a7026056030f21f4cf69f892c5a/src/index.ts#L252), which then compiles into the ` ./build/src/index.d.ts` file you referenced above. 

So the final, exported Logging class has an optional configuration field. See [examples](https://github.com/googleapis/nodejs-logging/blob/7cab3c5990c51a7026056030f21f4cf69f892c5a/src/index.ts#L252). But behind the scenes, before the logs are written to API, the library of course fills in the default required configurations.

**Comment by lukasschwab** [comment]
Thanks both of you for the responses here!

Our use case: we're fetching metadata about the log buckets associated with a given GCP project, _not_ writing logs or creating new log buckets. It'd be great to have the handwritten niceties you've built for the other APIs, but I know the log buckets feature is new.

This isn't causing problems for us now because it seems these services are non-null in practice. If they _were_ sometimes null, it'd be helpful to have more docs for how to prevent that... but it seems we're accidentally doing things right.

Thanks all for the detailed replies/your maintenance work!
